name: downsize
description: Pure dart image compression.
version: 1.0.0
repository: https://github.com/YassineDabbous/downsize
homepage: https://github.com/YassineDabbous/downsize
documentation: https://github.com/YassineDabbous/downsize/blob/main/doc/README.md

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  image: ^4.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
