name: downsize
description: Pure dart image compression across multiple formats, including JPG, PNG, GIF, BMP, TIFF, TGA, PVR, and ICO.
version: 1.1.0
repository: https://github.com/YassineDabbous/downsize
homepage: https://github.com/YassineDabbous/downsize
documentation: https://github.com/YassineDabbous/downsize/blob/main/README.md

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  image: ^4.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
